# Generated by Django 4.1.3 on 2022-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=25, verbose_name='producto')),
                ('precio_entrada', models.IntegerField(verbose_name='Valor entrada')),
                ('precio_salida', models.IntegerField(verbose_name='Precio de venta')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('distribuidor', models.CharField(max_length=25, verbose_name='Distribuidor')),
                ('facturas', models.CharField(max_length=25, verbose_name='Facturas')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('activo', models.BooleanField(default='True', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.ManyToManyField(to='inventarios.tipoproducto'),
        ),
    ]
