# Generated by Django 4.1.3 on 2022-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_productos_tipoproducto_delete_curso_productos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='distribuidor',
            fields=[
                ('distribuidor_id', models.AutoField(primary_key=True, serialize=False)),
                ('distribuidor_name', models.CharField(max_length=100)),
            ],
        ),
    ]
