# Generated by Django 4.1.3 on 2022-11-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_distribuidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='distribuidor',
        ),
        migrations.AddField(
            model_name='productos',
            name='distribuidor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.distribuidor'),
        ),
    ]
