# Generated by Django 4.1.3 on 2022-11-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_remove_productos_distribuidor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='distribuidor_id',
            new_name='Distribuidor',
        ),
    ]
