# Generated by Django 4.1.3 on 2022-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_rename_distribuidor_id_productos_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='producto'),
        ),
    ]
