# Generated by Django 4.1.3 on 2022-11-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_alter_productos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='facturas',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Facturas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_entrada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor entrada'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_salida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio de venta'),
        ),
    ]
