# Generated by Django 4.1.3 on 2022-11-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_alter_productos_cantidad_alter_productos_facturas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='distribuidor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
