# Generated by Django 4.1.3 on 2022-11-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_alter_distribuidor_distribuidor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
