# Generated by Django 4.1.3 on 2022-11-19 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.marca'),
        ),
    ]
