# Generated by Django 4.1.3 on 2022-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_productos_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo2',
            fields=[
                ('tipo2_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo2_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
