# Generated by Django 4.1.3 on 2022-11-19 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0011_tipo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Tipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.tipo2'),
        ),
    ]
