# Generated by Django 4.1.3 on 2022-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0013_alter_productos_precio_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo2',
            name='activo',
            field=models.BooleanField(default='True', max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_entrada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Valor entrada'),
        ),
    ]
