# Generated by Django 4.1.3 on 2022-12-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0014_tipo2_activo_alter_productos_precio_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo2',
            name='activo',
        ),
    ]
