# Generated by Django 4.1.3 on 2022-12-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0015_remove_tipo2_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='producto'),
        ),
    ]
